api_key: "ooPxxzLT1xgs8CWEiMjY"
test_dir: "/home/emma/facultad/pps/datasets/ppe-general/test"
models:
  # - name: "container-damage-detection-full/3"
  - name: "ppe-detection-yfmym/1"
  # - name: "container-segmentation-fgvew/3"
