target_classes:
  - "no-eyewear"
  - "no-gloves"
  - "no-mask"
  - "person"
target_size: 640 # Square only supported by now
target_dataset_path: "/home/emma/facultad/pps/datasets/ppe-detection-yolov8-dataset"
datasets:
  - origin: "/home/emma/Downloads/PPE_Detection_YOLOv8.v11-8-1-1-32-epoch.yolov11"
    fields_map:
      - source_field: "No - Goggles"
        target_field: "no-eyewear"
      - source_field: "No - Gloves"
        target_field: "no-gloves"
      - source_field: "Person"
        target_field: "person"
